USE [master]
GO
/****** Object:  Database [CommFilingDB]    Script Date: 19/02/2021 11:37:10 p. m. ******/
CREATE DATABASE [CommFilingDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CommFilingDB', FILENAME = N'C:\Users\Jhon Martinez\CommFilingDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CommFilingDB_log', FILENAME = N'C:\Users\Jhon Martinez\CommFilingDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [CommFilingDB] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CommFilingDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CommFilingDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CommFilingDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CommFilingDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CommFilingDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CommFilingDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CommFilingDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CommFilingDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CommFilingDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CommFilingDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CommFilingDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CommFilingDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CommFilingDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CommFilingDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CommFilingDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CommFilingDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [CommFilingDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CommFilingDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CommFilingDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CommFilingDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CommFilingDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CommFilingDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CommFilingDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CommFilingDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [CommFilingDB] SET  MULTI_USER 
GO
ALTER DATABASE [CommFilingDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CommFilingDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CommFilingDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CommFilingDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CommFilingDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CommFilingDB] SET QUERY_STORE = OFF
GO
USE [CommFilingDB]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
USE [CommFilingDB]
GO
/****** Object:  Schema [ADM]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE SCHEMA [ADM]
GO
/****** Object:  Schema [GEN]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE SCHEMA [GEN]
GO
/****** Object:  Schema [SEG]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE SCHEMA [SEG]
GO
/****** Object:  Table [ADM].[Action]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ADM].[Action](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](10) NOT NULL,
	[ActionName] [nvarchar](100) NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_Action] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ADM].[CorrespondenceType]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ADM].[CorrespondenceType](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](10) NOT NULL,
	[TypeName] [nvarchar](100) NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_CorrespondenceType] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [ADM].[Role]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [ADM].[Role](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Code] [nvarchar](10) NOT NULL,
	[RoleName] [nvarchar](100) NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_Role] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [GEN].[Audit]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GEN].[Audit](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[CreationUserId] [bigint] NOT NULL,
	[ModificationDate] [datetime2](7) NULL,
	[ModificationUserId] [bigint] NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_Audit] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [GEN].[Filing]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [GEN].[Filing](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[Consecutive] [nvarchar](14) NOT NULL,
	[StorageAddress] [nvarchar](1000) NULL,
	[Base64File] [nvarchar](max) NULL,
	[SenderUserId] [bigint] NOT NULL,
	[AddresseeUserId] [bigint] NOT NULL,
	[CorrespondenceTypeId] [bigint] NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_Filing] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [SEG].[RoleAction]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SEG].[RoleAction](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[RoleId] [bigint] NOT NULL,
	[ActionId] [bigint] NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_RoleAction] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SEG].[User]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SEG].[User](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](200) NOT NULL,
	[LastName] [nvarchar](200) NOT NULL,
	[NumberID] [nvarchar](50) NOT NULL,
	[Phonenumber] [nvarchar](30) NULL,
	[Email] [nvarchar](150) NULL,
	[ResidenceAddress] [nvarchar](250) NULL,
	[UserName] [nvarchar](50) NULL,
	[Password] [nvarchar](30) NULL,
	[AuditId] [bigint] NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SEG].[UserRole]    Script Date: 19/02/2021 11:37:11 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SEG].[UserRole](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [bigint] NOT NULL,
	[RoleId] [bigint] NOT NULL,
	[AuditId] [bigint] NOT NULL,
	[IsValid] [bit] NOT NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Action_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Action_AuditId] ON [ADM].[Action]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_CorrespondenceType_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_CorrespondenceType_AuditId] ON [ADM].[CorrespondenceType]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Role_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Role_AuditId] ON [ADM].[Role]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audit_CreationUserId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Audit_CreationUserId] ON [GEN].[Audit]
(
	[CreationUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Audit_ModificationUserId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Audit_ModificationUserId] ON [GEN].[Audit]
(
	[ModificationUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Filing_AddresseeUserId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Filing_AddresseeUserId] ON [GEN].[Filing]
(
	[AddresseeUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Filing_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Filing_AuditId] ON [GEN].[Filing]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Filing_CorrespondenceTypeId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Filing_CorrespondenceTypeId] ON [GEN].[Filing]
(
	[CorrespondenceTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Filing_SenderUserId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_Filing_SenderUserId] ON [GEN].[Filing]
(
	[SenderUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RoleAction_ActionId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_RoleAction_ActionId] ON [SEG].[RoleAction]
(
	[ActionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RoleAction_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_RoleAction_AuditId] ON [SEG].[RoleAction]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_RoleAction_RoleId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_RoleAction_RoleId] ON [SEG].[RoleAction]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_User_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_User_AuditId] ON [SEG].[User]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserRole_AuditId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_UserRole_AuditId] ON [SEG].[UserRole]
(
	[AuditId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserRole_RoleId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_UserRole_RoleId] ON [SEG].[UserRole]
(
	[RoleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserRole_UserId]    Script Date: 19/02/2021 11:37:11 p. m. ******/
CREATE NONCLUSTERED INDEX [IX_UserRole_UserId] ON [SEG].[UserRole]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [ADM].[Action]  WITH CHECK ADD  CONSTRAINT [FK_Action_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [ADM].[Action] CHECK CONSTRAINT [FK_Action_Audit_AuditId]
GO
ALTER TABLE [ADM].[CorrespondenceType]  WITH CHECK ADD  CONSTRAINT [FK_CorrespondenceType_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [ADM].[CorrespondenceType] CHECK CONSTRAINT [FK_CorrespondenceType_Audit_AuditId]
GO
ALTER TABLE [ADM].[Role]  WITH CHECK ADD  CONSTRAINT [FK_Role_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [ADM].[Role] CHECK CONSTRAINT [FK_Role_Audit_AuditId]
GO
ALTER TABLE [GEN].[Audit]  WITH CHECK ADD  CONSTRAINT [FK_Audit_User_CreationUserId] FOREIGN KEY([CreationUserId])
REFERENCES [SEG].[User] ([Id])
GO
ALTER TABLE [GEN].[Audit] CHECK CONSTRAINT [FK_Audit_User_CreationUserId]
GO
ALTER TABLE [GEN].[Audit]  WITH CHECK ADD  CONSTRAINT [FK_Audit_User_ModificationUserId] FOREIGN KEY([ModificationUserId])
REFERENCES [SEG].[User] ([Id])
GO
ALTER TABLE [GEN].[Audit] CHECK CONSTRAINT [FK_Audit_User_ModificationUserId]
GO
ALTER TABLE [GEN].[Filing]  WITH CHECK ADD  CONSTRAINT [FK_Filing_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [GEN].[Filing] CHECK CONSTRAINT [FK_Filing_Audit_AuditId]
GO
ALTER TABLE [GEN].[Filing]  WITH CHECK ADD  CONSTRAINT [FK_Filing_CorrespondenceType_CorrespondenceTypeId] FOREIGN KEY([CorrespondenceTypeId])
REFERENCES [ADM].[CorrespondenceType] ([Id])
GO
ALTER TABLE [GEN].[Filing] CHECK CONSTRAINT [FK_Filing_CorrespondenceType_CorrespondenceTypeId]
GO
ALTER TABLE [GEN].[Filing]  WITH CHECK ADD  CONSTRAINT [FK_Filing_User_AddresseeUserId] FOREIGN KEY([AddresseeUserId])
REFERENCES [SEG].[User] ([Id])
GO
ALTER TABLE [GEN].[Filing] CHECK CONSTRAINT [FK_Filing_User_AddresseeUserId]
GO
ALTER TABLE [GEN].[Filing]  WITH CHECK ADD  CONSTRAINT [FK_Filing_User_SenderUserId] FOREIGN KEY([SenderUserId])
REFERENCES [SEG].[User] ([Id])
GO
ALTER TABLE [GEN].[Filing] CHECK CONSTRAINT [FK_Filing_User_SenderUserId]
GO
ALTER TABLE [SEG].[RoleAction]  WITH CHECK ADD  CONSTRAINT [FK_RoleAction_Action_ActionId] FOREIGN KEY([ActionId])
REFERENCES [ADM].[Action] ([Id])
GO
ALTER TABLE [SEG].[RoleAction] CHECK CONSTRAINT [FK_RoleAction_Action_ActionId]
GO
ALTER TABLE [SEG].[RoleAction]  WITH CHECK ADD  CONSTRAINT [FK_RoleAction_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [SEG].[RoleAction] CHECK CONSTRAINT [FK_RoleAction_Audit_AuditId]
GO
ALTER TABLE [SEG].[RoleAction]  WITH CHECK ADD  CONSTRAINT [FK_RoleAction_Role_RoleId] FOREIGN KEY([RoleId])
REFERENCES [ADM].[Role] ([Id])
GO
ALTER TABLE [SEG].[RoleAction] CHECK CONSTRAINT [FK_RoleAction_Role_RoleId]
GO
ALTER TABLE [SEG].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [SEG].[User] CHECK CONSTRAINT [FK_User_Audit_AuditId]
GO
ALTER TABLE [SEG].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Audit_AuditId] FOREIGN KEY([AuditId])
REFERENCES [GEN].[Audit] ([Id])
GO
ALTER TABLE [SEG].[UserRole] CHECK CONSTRAINT [FK_UserRole_Audit_AuditId]
GO
ALTER TABLE [SEG].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_Role_RoleId] FOREIGN KEY([RoleId])
REFERENCES [ADM].[Role] ([Id])
GO
ALTER TABLE [SEG].[UserRole] CHECK CONSTRAINT [FK_UserRole_Role_RoleId]
GO
ALTER TABLE [SEG].[UserRole]  WITH CHECK ADD  CONSTRAINT [FK_UserRole_User_UserId] FOREIGN KEY([UserId])
REFERENCES [SEG].[User] ([Id])
GO
ALTER TABLE [SEG].[UserRole] CHECK CONSTRAINT [FK_UserRole_User_UserId]
GO
USE [master]
GO
ALTER DATABASE [CommFilingDB] SET  READ_WRITE 
GO
